[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false
idl-build = ["anchor-lang/idl-build"]

[programs.localnet]
relay = "DevpMzGDfkVPuzkGY19S1KDP86YWKECqJ1cSwuVieiD4"

[programs.devnet]
relay = "DevpMzGDfkVPuzkGY19S1KDP86YWKECqJ1cSwuVieiD4"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"    
wallet = "/root/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/nx run anchor:jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
